#spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false

server:
  error:
    path: /globalError

cat-api:
  url: https://api.thecatapi.com/v1/images/search
